default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Run gradlew build"
  lane :build do
    gradle(task: "build")
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    upload_to_play_store(track: "beta")
  end
end
