default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Run gradlew build"
  lane :build do
    gradle(
      task: "assemble",
      build_type: "Debug",
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean")
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
    )
    upload_to_play_store(track: "beta")
  end
end
