name: Develop Branch Test & Build
on:
  push:
  pull_request:
    types: [opened]
jobs:
  main:
    name: Test & Build Debug
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - name: Run Fastlane Build Lane
        run: fastlane build
      - name: Save Artifact
        uses: actions/upload-artifact@v1
        with:
          name: debug-app
          path: app/build/outputs/apk/debug/app-debug.apk

