name: Android Pull Request & Master CI

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
      - 'signed-release'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace

  debug-apk:
      needs: [test]
      name: Generate Debug APK
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload Debug APK
          uses: actions/upload-artifact@v1
          with:
            name: debug-app
            path: app/build/outputs/apk/debug/app-debug.apk

  release-apk:
      needs: [test]
      name: Generate Release APK
      runs-on: ubuntu-18.04

      steps:
        - uses: actions/checkout@v1
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Decrypt secrets
          run: bash ./decrypt_secrets.sh
          env:
            KEY_STORE_PASSPHRASE: ${{ secrets.KEY_STORE_PASSPHRASE }}
            APP_SIGN_KEY_FILE_PASSPHRASE: ${{ secrets.APP_SIGN_KEY_FILE_PASSPHRASE }}
        - name: Build Release APK
          run: bash ./gradlew build --stacktrace
        - name: Upload Release APK
          uses: actions/upload-artifact@v1
          with:
            name: release-app
            path: app/build/outputs/apk/release/app-release.apk

